PREFIX time: <http://opendatacommunities.org/def/ontology/time/>
PREFIX geo: <http://opendatacommunities.org/def/ontology/geography/>
PREFIX gov: <http://opendatacommunities.org/def/local-government/>
PREFIX osgeo:  <http://data.ordnancesurvey.co.uk/ontology/admingeo/>
PREFIX year: <http://reference.data.gov.uk/id/government-year/>
PREFIX cube: <http://purl.org/linked-data/cube#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX building: <http://opendatacommunities.org/def/ontology/house-building/>
PREFIX starts: <http://opendatacommunities.org/def/ontology/house-building/starts/>
PREFIX compl: <http://opendatacommunities.org/def/ontology/house-building/completions/>

SELECT ?refArea ?observation ?gssCode ?authorityName ?completions ?starts ?observation2 WHERE { 

   GRAPH <http://opendatacommunities.org/graph/house-building/completions/tenure> { 
      ?observation rdf:type cube:Observation ;
                   time:refPeriod year:2012-2013 ; 
                   geo:refArea ?refArea ; 
                   compl:tenure <http://opendatacommunities.org/def/concept/general-concepts/tenure/all> ;
                   building:completionsObs ?completions .
   }

   GRAPH <http://opendatacommunities.org/graph/house-building/starts/tenure> { 
      ?observation2 rdf:type cube:Observation ;
                    time:refPeriod year:2012-2013 ; 
                    starts:tenure <http://opendatacommunities.org/def/concept/general-concepts/tenure/all> ;
                    geo:refArea ?refArea ; 
                    building:startsObs ?starts .
   }

   GRAPH <http://opendatacommunities.org/graph/ontology/geography/ons-labels> {
     ?refArea osgeo:gssCode ?gssCode ; 
              gov:isGovernedBy ?authority .
   }

   GRAPH <http://opendatacommunities.org/graph/local-authorities> { 
      ?authority rdfs:label ?authorityName .
   }

} ORDER BY(?authorityName)

